import os

def getPaths(entry, paths):
    """Takes the absolute path of a SPASE record directory to be walked to extract all SPASE records present. 
    Returns these paths using the list parameter paths, which holds the absolute paths generated by the function.
    
    :param entry: A string of the absolute path of the SPASE record directory to be searched/walked to find all 
        SPASE records within.
    :type entry: String
    :param paths: A list to hold absolute paths of all SPASE records found within the given directory
    :type paths: list
    :return: A list containing the absolute paths of all SPASE records found within the given directory.
    :rtype: list
    """
    if os.path.exists(entry):
        for root, dirs, files in os.walk(entry):
            if files:
                for file in files:
                    paths.append(root + "/" + file)
    else:
        print(entry + " does not exist")
    return paths